#!/bin/bash  
#PBS -k o  
#PBS -l nodes=1:ppn=4,walltime=200:00:00  
#PBS -N trim 
#PBS -j oe  
#PBS -V 
module load openmpi-1.6.3
module load open64
module load Trimmomatic

mpirun
	java -jar /share/apps/Installs/walls/Trimmomatic-0.33/trimmomatic-0.33.jar PE -phred33	BI-F1-200-3_CGGCTATG-CAGGACGT_L001_R1_001.fastq.gz BI-F1-200-3_CGGCTATG-CAGGACGT_L001_R2_001.fastq.gz output_forward_paired.fq.gz output_forward_unpaired.fq.gz output_reverse_paired.fq.gz output_reverse_unpaired.fq.gz ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 

